; PlatformIO Project Configuration File
; ESP32 water meter firmware.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
	adafruit/Adafruit LIS3MDL@^1.2.5
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.4.2
